# **PYTHON**

## **List**

In [ ]:
#List:
alwlaeed = [1, 2, 3, 4, 5]
x= ['a','b','c']
print(x[0])

a


In [ ]:
#List function
x= ['a','b','c']
x.append('d')
print(x)

['a', 'b', 'c', 'd']


In [ ]:
#List insert
x=['a','b','c']
x.insert(2,'d')
print(x)

['a', 'b', 'd', 'c']


In [ ]:
#list Remove
x=['a','b','c']
x.remove('a')
print(x)


['b', 'c']


In [ ]:
#list Delete
x=['a','b','c']
del x[1]
print(x)

['a', 'c']


In [ ]:
# list length
x=['a','b','c']
print(len(x))

3


In [ ]:
#pop
x=['a','b','c']
x.pop()
print(x)

['a', 'b']


In [ ]:
#slicing
x=['a','b','c']
print(x[1:3])
#slicing
x=['a','b','c']
print(x[:3])
#slicing
x=['a','b','c']
print(x[1:])
#slicing
x=['a','b','c']
print(x[1:-1])

['b', 'c']
['a', 'b', 'c']
['b', 'c']
['b']


In [ ]:
#extend
x=['a','b','c']
y=['d','e','f']
x.extend(y)
print(x)

#extend
x=['a','b','c']
y=['d','e','f']
z=[]
z.extend(x)
z.extend(y)
print(z)

['a', 'b', 'c', 'd', 'e', 'f']
['a', 'b', 'c', 'd', 'e', 'f']


In [ ]:
#count
x=['a','b','b','b','c']
print(x.count('b'))

3


In [ ]:
#in
x=['a','b','c']
y = 'b'in x
print(y)

True


In [ ]:
#index
x=['a','b','c']
print(x.index('b'))

1


In [ ]:
#sort
x=['c','b','a']
x.sort()
print(x)
#sort
x=['c','a','b']
x.sort(reverse =True)
print(x)

['a', 'b', 'c']
['c', 'b', 'a']


In [ ]:
x=['c','b','a']
print(sorted(x))
print(x)

['a', 'b', 'c']
['c', 'b', 'a']


In [ ]:
#join two list with +
x=['a','b','c']
y=['d','e','f']
z= x+y
print(z)



['a', 'b', 'c', 'd', 'e', 'f']


In [ ]:
#copy
x=['a','b','c']
y=x.copy()
print(y)

['a', 'b', 'c']


In [ ]:
#Clear
x=['a','b','c']
x.clear()
print(x)

[]


Tuple

## **Tuple**

In [ ]:
#tuple
x=(1,2,3,4,5)
print(x)

In [ ]:
#tuple
x=(1,2,3,4,5)
print(x[2])
print(x[0:2])

3
(1, 2)


In [ ]:
#check
x=(1,2,3,4,)
y = 2 in x
print(y)

True


In [ ]:
#join
x=(1,2,3,4,)
y=(5,6,7,8,)
z=x+y
print(z)

(1, 2, 3, 4, 5, 6, 7, 8)


In [ ]:
#tuple to list
x=(1,2,3,4,)
y=list(x)
print(y)

[1, 2, 3, 4]


In [ ]:
#list to tuple
x=[1,2,3,4,]
y=tuple(x)
print(y)

(1, 2, 3, 4)


## **Set**

In [ ]:
#set
x={2,3,4,5,5,1}
print(x)

{1, 2, 3, 4, 5}


In [ ]:
#add
x={2,3,4,5,5,1}
x.add(6)
print(x)

{1, 2, 3, 4, 5, 6}


In [ ]:
#update
x={2,3,4,5,5,1}
y={6,7,8,9}
x.update(y)
print(x)

{1, 2, 3, 4, 5, 6, 7, 8, 9}


In [ ]:
#remove
x={2,3,4,5,5,1}
x.remove(5)
print(x)

{1, 2, 3, 4}


In [ ]:
#discard
x={2,3,4,5,5,1}
x.discard(2)
print(x)

{1, 3, 4, 5}


In [ ]:
#pop
x={2,3,4,5,5,1}
x.pop()
print(x)

{2, 3, 4, 5}


In [ ]:
#clear
x={2,3,4,5,5,1}
x.clear()
print(x)

set()


In [ ]:
#delete
x={2,3,4,5,5,1}
del x


In [ ]:
#union
x={1,2,3}
y={4,5,6,2}
z=x.union(y)
print(z)


{1, 2, 3, 4, 5, 6}


In [ ]:
#intersection
x={1,2,3}
y={4,5,6,2}
z=x.intersection(y)
print(z)

{2}


In [ ]:
#intersection_update
x={1,2,3}
y={4,5,6,2}
x.intersection_update(y)
print(x)


{2}


In [ ]:
#symmetrice_difference_update
x={1,2,3}
y={4,5,6,2}
x.symmetric_difference_update(y)
print(x)

{1, 3, 4, 5, 6}


In [ ]:
#issubset
x={1,2,3,4}
y={4,5,6,2,1,3}
z=x.issubset(y)
print(z)

True


In [ ]:
#is dis joint
x={1,2,3,4}
y={5,6,1}
z=x.isdisjoint(y)
print(z)

False


## **Dictionary**

In [ ]:
#dictionary
x={
    'x':1,
    'y':2,
    'z':3
}
print(x)

{'x': 1, 'y': 2, 'z': 3}


In [ ]:
#dictionary
x={
    'x':1,
    'y':2,
    'z':3
}
print(x['y'])

2


In [ ]:
#dictionary
x={
    'x':1,
    'y':2,
    'z':3
}
print(x.get('y'))

2


In [ ]:
#dictionary
x={
    'x':1,
    'y':2,
    'z':3
}
print(x.keys())

dict_keys(['x', 'y', 'z'])


In [ ]:
#dictionary
x={
    'x':1,
    'y':2,
    'z':3
}
print(x.values())

dict_values([1, 2, 3])


In [ ]:
#dictionary
x={
    'x':1,
    'y':2,
    'z':3
}
print(x.items())

dict_items([('x', 1), ('y', 2), ('z', 3)])


In [ ]:
#Add
x={
    'x':1,
    'y':2,
    'z':3
}
x['c']=5
print(x)


{'x': 1, 'y': 2, 'z': 3, 'c': 5}


In [ ]:
#update
x={
    'x':1,
    'y':2,
    'z':3
}
x.update({'y':5})
print(x)

x={
    'x':1,
    'y':2,
    'z':3
}
x['x']=5
print(x)

{'x': 1, 'y': 5, 'z': 3}
{'x': 5, 'y': 2, 'z': 3}


In [ ]:
#pop
x={
    'x':1,
    'y':2,
    'z':3
}
x.pop('y')
print(x)

{'x': 1, 'z': 3}


In [ ]:
#popitem
x={
    'x':1,
    'y':2,
    'z':3
}
x.popitem()
print(x)

{'x': 1, 'y': 2}


In [ ]:
#delete
x={
    'x':1,
    'y':2,
    'z':3
}
del x['y']
print(x)

{'x': 1, 'z': 3}


In [ ]:
#clear
x={
    'x':1,
    'y':2,
    'z':3
}
x.clear()
print(x)

{}


In [ ]:
#copy
x={
    'x':1,
    'y':2,
    'z':3
}
y=x.copy()
print(y)

{'x': 1, 'y': 2, 'z': 3}


In [ ]:
#nested dictionary
x={
    'x':{'Alwaleed':1,'ali':3},
    'y':{'Alwaleed':2}

}
print(x)
print(x['x'])
print(x['x']['Alwaleed'])
print(x['x']['ali'])

{'x': {'Alwaleed': 1, 'ali': 3}, 'y': {'Alwaleed': 2}}
{'Alwaleed': 1, 'ali': 3}
1
3


In [ ]:
#nested dictionary
x={
    'x':[1,2,3,4],
    'y':{'Alwaleed':2}

}
print(x)
print(x['x'])
print(x['x'][2])
print(x['y']['Alwaleed'])


{'x': [1, 2, 3, 4], 'y': {'Alwaleed': 2}}
[1, 2, 3, 4]
3
2


In [ ]:
#nested list
x=[{'a':1,'b':2},{'c':3,'d':4},{'z':3,'f':4}]
print(x)
print(x[0])
print(x[0]['a'])

[{'a': 1, 'b': 2}, {'c': 3, 'd': 4}, {'z': 3, 'f': 4}]
{'a': 1, 'b': 2}
1


## **Condition:IF**

In [ ]:
#equals : a==b
#not equal : a!=b
#less than : a<b
#greater than : a>b
#greater than or equal : a>=b
#less than or equal : a<=b



In [ ]:
#if
a=4
b=6
if a>b :
  print(a)
print('aaa')


aaa


In [ ]:
#els if
a=10
b=6
if a>b :
  print(a)
elif b>a :
    print(b)


10


In [ ]:
#else
a=6
b=6
if a>b :
  print(a)
elif b>a :
    print(b)
else :
  print('aaa')

aaa


In [ ]:
#short hand if
a = 4
b= 6
print(a) if a>b else print(b)

6


6


## **While**

In [ ]:
#while
i=1
while i<6 :
  print(i)
  i+=1

1
2
3
4
5


In [ ]:
#break statment
i= 0
while i<6 :
    i+=1
    print(i)
    if i==3:
     break


1
2
3


In [ ]:
#continue statment
i= 0
while i<6 :
  i+=1
  if i==3:
    continue
  print(i)


1
2
4
5
6


## **For loop**

In [ ]:
x=['a','b','c']
for i in x:
  print(i)

a
b
c


In [ ]:
for i in 'alwaleed':
  print(i)

a
l
w
a
l
e
e
d


In [ ]:
for i in range(0,6):
  print(i)


0
2
4


In [ ]:
for x in range(0,6):
  print(x)
else :
  print('end')


0
1
2
3
4
5
end


In [ ]:
#nested loop
x=['a','b','c']
y=[1,2,3]
for i in x:
  for z in y:
    print(i,z)

a 1
a 2
a 3
b 1
b 2
b 3
c 1
c 2
c 3


## **Function**

In [ ]:
def alwaleed():
  print('Alwaleed')
alwaleed()


Alwaleed


In [ ]:
def f(name):
  print(name + ' fname')

f('alwaleed')

alwaleed fname


In [ ]:
def f(fname,lname):
  print(fname +' '+lname)

f('alwaleed','Khaled')

alwaleed Khaled


In [ ]:
#args
def f(*t):
  print(t)

f('alwaleed','Khaled')

('alwaleed', 'Khaled')


In [ ]:
def f(x,y,z):
  print(x)
f(z='ali',x='alaa',y='moh')

alaa


In [ ]:
def f(**t):
  print(t)
f(z='ali',x='alaa',y='moh')

{'z': 'ali', 'x': 'alaa', 'y': 'moh'}


In [ ]:
#return
def f(x):
  return 5*x
f(5)

25

In [ ]:
#recursion
def f(n):
  print(n)
  if n==0:
     return
  f(n-1)
  print(n)


f(5)

5
4
3
2
1
0
1
2
3
4
5


In [ ]:
#recursion
def f(n):

  if n==0:
     return
  f(n-1)
  print(n)


f(5)

1
2
3
4
5


In [ ]:
#recursion
def f(n):

  if n==0:
     return 1
  return f(n-1)*n


print(f(5))

120


In [ ]:
#lambda
x=lambda a:a+10
print(x(5))



15


In [ ]:
def factorial(n):
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result

print(factorial(5))

120


## **Class**

In [ ]:
class alwaleed:
  x=5

a=alwaleed()
print(a.x)

5


In [ ]:
class alwaleed:
  def __init__(self, d):
    self.d=d
    self.x=5
    self.f=self.x + self.d

#main code
a=alwaleed(4)
print(a.f)

9


In [ ]:
class alwaleed:
  def sum(self,x,y):
    print(x+y)

a=alwaleed()
a.sum(3,4)

7


In [ ]:
class alwaleed:
  @classmethod
  def sum(cls,x,y):
    print(x+y)

alwaleed.sum(3,4)

7


In [ ]:
class alwaleed:
  @staticmethod
  def sum(x,y):
    print(x+y)

alwaleed.sum(3,4)

7


In [ ]:
class person:
  def __init__(self,fn,ln):
    self.fn=fn
    self.ln=ln
    print(self.fn,self.ln)

  def printname(self):
    print(self.fn,self.ln)

class student(person):
  pass

x=student('alwaleed','khaled')
print(x.ln)
x.printname()


alwaleed khaled
alwaleed khaled
khaled


In [ ]:
class person:
  def __init__(self,fn,ln):
    self.fn=fn
    self.ln=ln
    print(self.fn,self.ln)



class student(person):
  pass

x=student('alwaleed','khaled')


alwaleed khaled


In [ ]:
#polymorphism
class vehicle:
  def __init__(self,name,color,price):
    self.name=name
    self.color=color
    self.price=price
  def move(self):
    print("vehicle is moving")
  def info(self):
    print(f"Name:{self.name},color:{self.color},price:{self.price}")

class car(vehicle):
  def move(self):
    print("car is moving")
class boat(vehicle):
  def move(self):
    print("boat is moving")
class plane(vehicle):
  def move(self):
    print("plane is moving")

car = car("car", "red", 20000)
boat = boat("boat", "blue", 10000)
plane = plane("plane", "white", 50000)

car.move()
car.info()

boat.move()
boat.info()

plane.move()
plane.info()


car is moving
Name:car,color:red,price:20000
boat is moving
Name:boat,color:blue,price:10000
plane is moving
Name:plane,color:white,price:50000


In [ ]:
#abstraction
from abc import ABC,abstractmethod
class vehicle:
  def __init__(self,name):
    self.name=name
  @abstractmethod
  def move(self):
    print("vehicle is moving")
  def info(self):
    print(f"Name:{self.name}")

class car(vehicle):
  def move(self):
    print("car is moving")
class boat(vehicle):
  def move(self):
    print("boat is moving")
class plane(vehicle):
  def move(self):
    print("plane is moving")

car = car("car")
boat = boat("boat")
plane = plane("plane")

car.move()
car.info()


car is moving
Name:car
boat is moving
Name:boat
plane is moving
Name:plane


## **Json**

In [ ]:
#convert json to python
import json
json_data='{"name":"alwaleed","age":20}'
phthon_dick=json.loads(json_data)
print(phthon_dick)

{'name': 'alwaleed', 'age': 20}


In [ ]:
#convert python to json
data={
    "name":"alwaleed",
    "age":20,
    "city":"amman"
}
json_string=json.dumps(data)
print(json_string)


{"name": "alwaleed", "age": 20, "city": "amman"}


## **NumPy**

In [ ]:
import numpy as np
x=np.array(4)
y=np.array([1,2,3,4])
z=np.array([[1,2,3],[4,5,6]])
cc=np.array(
    [
        [
          [1,2,3],
          [4,5,6]
                  ],
         [
          [1,2,3],
          [4,5,6]
                  ]
        ]
    )
print(x)
print(y)
print(z)
print(cc)
print(x.ndim)
print(y.ndim)
print(z.ndim)
print(cc.ndim)

print(x)
print(y[0])
print(z[0,1])
print(cc[0,1,2])

4
[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
0
1
2
3
4
1
2
6


In [ ]:
#copy
x=np.array([1,2,3,4])
y=x.copy()
x[0]=10
print(x)
print(y)
print(y.base)

[10  2  3  4]
[1 2 3 4]
None


In [ ]:
#view
x=np.array([1,2,3,4])
y=x.view()
x[0]=10
print(x)
print(y)
print(y.base)

[10  2  3  4]
[10  2  3  4]
[10  2  3  4]


In [ ]:
#shape
x=np.array([1,2,3,4])
y=np.array([[1,2,3],[4,5,6]])
z=np.array(
    [
        [
          [1,2,3],
          [4,5,6]
                  ],
         [
          [1,2,3],
          [4,5,6]
                  ]
        ]
    )
print(x.shape)
print(y.shape)
print(z.shape)

(4,)
(2, 3)
(2, 2, 3)


In [ ]:
#reshape
z=np.array([[1,2,3],[4,5,6]])
print(z)
print(z.shape)

x=z.reshape(3,2)
print(x.shape)
print(x)


[[1 2 3]
 [4 5 6]]
(2, 3)
(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#for loop 1d
z=np.array([1,2,3,4,5,6])
for i in z:
  print(i)

1
2
3
4
5
6


In [ ]:
#iteration 2d
z=np.array([[1,2,3],[4,5,6]])
for i in x:
  for j in i:
    print(j)

1
2
3
4
5
6


In [ ]:
#nditer
x=np.array([[1,2,3],[4,5,6]])
for i in np.nditer(x):
  print(i)

1
2
3
4
5
6


## **Python Practical Problem-Solving Qustions**

In [227]:
from typing import Counter
#list:1
x=[1,2,3,4,5,6,7,8,9,10]
for i in range(2,len(x)+1,2):
  print(i)
print('end list 1')

#list:2
def r (list1,list2):
  for i in list1:
    if i in list2:
      print(i)
r([1,2,3,4,5],[4,5,6,7,8])
print('end list 2')

#list:3
x = [1, 2, 3, 4, 5, 6, 7]

for i in range(len(x), 0, -1):
    print(i)
print('end list 3')

#list:4
x=[1,2,3,4,5,6,7]
total =0
for i in x:
  total += i
print(total)
print('end list 4')

#list:5
x=[2,1,3,4,5,6,7]
x.sort()
print(x[-2])
print('end list 5')
###########################################################
#tuple:1
x=(1,2,3,4,5)
print(x[0])
print(x[-1])
print('end tuple 1')

#tuple:2
def r(t):

    lst = list(t)
    lst[0], lst[-1] = lst[-1], lst[0]
    return tuple(lst)

x = (1, 2, 3, 4, 5)
x = r(x)
print(x)
print('end tuple 2')

#tuple:3
x=(2,1,3,4,5)
y=list(x)
y.sort()
x=tuple(y)
print(x)
print('end tuple 3')

#tuple:4
x=(2,1,3,4,5)
c= Counter(x)
print(c)

print('end tuple 4')

###############################################
#dictionary:1
x={'Ali':40,'Ahmad':75,'Alwaleed':80,'Alaa':70,'Salim':35}

for i in x.keys():
  if x[i]>=50:
    print(i)
print('end dictionary 1')


#dictionary:2
def r(x,y):
  x.update(y)
  return x
x={'Ali':40,'Ahmad':75,'Alwaleed':80,'Alaa':70,'Salim':35}
y={'x':40,'y':75,'z':80,'r':70,'s':35}
r(x,y)
print(x)
print('end dictionary 2')

#dictionary:3
x={'Ali':40,'Ahmad':75,'Alwaleed':80,'Alaa':70,'Salim':35}
y=list(x.values())
y.sort()
z=y[-1]
for key, value in x.items():
    if value == z:
        print(key)
###########################################################
#set:1
x={1,2,3,4,5}
y={4,5,6,7,8}
z=x.intersection(y)
x.update(y)
print(z)
print(x)
print('end set 1')

#set:2
x=[1,2,3,3,4,5]
z=set(x)
y=list(z)
print(y)

print('end set 2')

#set:3
def r(x,y):
  z=x.isdisjoint(y)
  return z

x={1,2,3,4,5}
y={4,5,6,7,8}

print(r(x,y))
print('end set 3')

#set:4
x={1,2,3,4,5}
y={4,5,6,7,8}
x.symmetric_difference_update(y)
print(x)
print('end set 4')

#####################################################
#if:1
x=1
if x>0 :
  print('p')
elif x<0:
  print('n')
else:
  print('z')

print('end if:1')

#if:2
def r(year):
    if (year % 4 == 0) and (year % 100 != 0 or year % 400 == 0):
        return True
    else:
        return False


year = 2025
print(r(year))
print('end if:2')

#if:3
def r(c):
 ch='aeiouAEIOU'
 if c in ch:
   print('vowel')
 else:
   print('consonant')
r('c')
print('end if:3')
###################################################
#while loop:1
i=0
while i<=100:
  i+=1
  if i%17==0:
    break
  print(i)

print('end while:1')

#while loop:2
total = 0

while True:
    #num = int(input("أدخل رقمًا (أدخل -1 للتوقف): "))
    num=-1
    if num == -1:
        break
    total += num

print("المجموع:", total)
print('end while:2')

#while loop:3
i = 0
while i < 50:
    i += 1
    if i % 2 == 0:
        continue
    print(i)

print('end while:3')
###################################################

#for loop:2
def r(n):
    for i in range(0,11):
      print(f"{n} * {i} = {i * x}")

r(8)
print('end for loop:1')

#for loop:2
x='alwleed'
vowels = 'aeiouAEIOU'
count=0
for i in x:
  if i in vowels:
    count+=1
print(count)
print('end for loop:2')

#for loop:3
x=[1,2,3,4,5,6,7,8,9,10,11]
for i in x:
  if i<6:
    continue
  print(i)

print('end for loop:3')
########################################################
#function:1
def r(num):
  re=1
  for i in range(1,num+1):
    re*=i

  print(re)

r(5)
print('end function:1')

#function:2
def r(text):
    return text == text[::-1]


print(r('dad'))
print('end function:2')

#function:3
def r(lst):
    result = []
    for i in lst:
        result.append(i * i)
    return result

print(r([1, 2, 3, 4, 5]))
print('end function:3')
##################################################
#recursion:1
def r(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return r(n-1) + r(n-2)

print(r(5))
print(r(8))
print('end recursion:1')

#recursion:2
def power(base, exponent):
    if exponent == 0:
        return 1
    else:
        return base * power(base, exponent - 1)

print(power(2, 3))
print('end recursion:2')

#recursion:3
def r(lst):
    if len(lst) == 0:
        return 0
    else:
        return lst[0] + r(lst[1:])
numbers = [1, 2, 3, 4, 5]
result = r(numbers)
print(result)
print('end recursion:3')
###############################################################
#break&&continue:1
for i in range(1, 21):
    if i % 3 == 0:
        continue

    print(i)
print('end break&&continue:1')

#break&&continue:2
for i in range(1, 51):
    if i % 7 == 0 and i % 13 == 0:
        break
    print(i)

print('end break&&continue:2')

#break&&continue:2
def r(lst):
    for i in lst:
        if i % 2 == 0:
            break
        print(i)

r([1, 2, 3, 4, 5])
print('end break&&continue:3')
########################################################
#class:1
class Car:

    def __init__(self, brand, model):
        self.brand = brand
        self.model = model


    def display_info(self):
        print(f"العلامة التجارية: {self.brand}")
        print(f"الموديل: {self.model}")

# اختبار الكود:
car1 = Car("تويوتا", "كورولا")
car1.display_info()

car2 = Car("فورد", "سكيب")
car2.display_info()
print('end class:1')

#class:2
class MyClass:

    count = 0


    def __init__(self):

        MyClass.count += 1


    @classmethod
    def get_object_count(cls):
        return cls.count


obj1 = MyClass()
obj2 = MyClass()
obj3 = MyClass()


print(f"عدد الكائنات التي تم إنشاؤها: {MyClass.get_object_count()}")
print('end class:2')
#class:3


class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def display_info(self):
        print(f"الاسم: {self.name}, العمر: {self.age}")


class Student(Person):
    def study(self):
        print(f"{self.name} يدرس بجد.")

student1 = Student("خالد", 20)
student1.display_info()
student1.study()
print('end class:3')

#class : 4
class Dog:
    def make_sound(self):
        print("الكلب ينبح!")

class Cat:
    def make_sound(self):
        print("القطة تموء!")

dog = Dog()
cat = Cat()

for animal in (dog, cat):
    animal.make_sound()
print('end class:4')

##############################################
#json:1
import json


data = {
    "name": "Ali",
    "age": 25,
    "city": "Riyadh"
}

json_string = json.dumps(data)


print(json_string)
################################################################3
import numpy as np

arr = np.array([[0,0,0,0], [0,0,0,0]])  # قائمة داخل قائمة

print(arr)
print('end numpy:1')
#numpy:2
import numpy as np

arr = np.array([1, 2, 3,70,55,10,14, 4, 5,88])

print(arr)
print('end numpy:2')
#numpy:3
import numpy as np
arr = np.array([1, 2, 3,70,55,10,14, 4, 5,88])

print(np.mean(arr))

print(np.median(arr))

print(np.std(arr))

print(arr)
print('end numpy:3')
#numpu:4
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
z= arr.reshape(3, 2)
print(z)
print('end numpy:4')
#numpy:5
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])
re =arr1+arr2
print(re)
print('end numpy:5')

#numpy:6
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])
re =arr1*arr2
print(re)
print('end numpy:6')
#numpy:7

import numpy as np
arr1 = np.array([[1,2,3],[4,5,6],[1,2,3]])
print(arr1[:3, :2])















2
4
6
8
10
end list 1
4
5
end list 2
7
6
5
4
3
2
1
end list 3
28
end list 4
6
end list 5
1
5
end tuple 1
(5, 2, 3, 4, 1)
end tuple 2
(1, 2, 3, 4, 5)
end tuple 3
Counter({2: 1, 1: 1, 3: 1, 4: 1, 5: 1})
end tuple 4
Ahmad
Alwaleed
Alaa
end dictionary 1
{'Ali': 40, 'Ahmad': 75, 'Alwaleed': 80, 'Alaa': 70, 'Salim': 35, 'x': 40, 'y': 75, 'z': 80, 'r': 70, 's': 35}
end dictionary 2
Alwaleed
{4, 5}
{1, 2, 3, 4, 5, 6, 7, 8}
end set 1
[1, 2, 3, 4, 5]
end set 2
False
end set 3
{1, 2, 3, 6, 7, 8}
end set 4
p
end if:1
False
end if:2
consonant
end if:3
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
end while:1
المجموع: 0
end while:2
1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
end while:3
8 * 0 = 0
8 * 1 = 1
8 * 2 = 2
8 * 3 = 3
8 * 4 = 4
8 * 5 = 5
8 * 6 = 6
8 * 7 = 7
8 * 8 = 8
8 * 9 = 9
8 * 10 = 10
end for loop:1
3
end for loop:2
6
7
8
9
10
11
end for loop:3
120
end function:1
True
end function:2
[1, 4, 9, 16, 25]
end function:3
5
21
end recursion:1
8
end recursion:2
15
end recursio